### ISSUE TITLE
Add auto-updating

### ISSUE THREAD

**Issue by WheresAlice** [staticli/staticli#16]
Based on the bintray API and go-update

https://api.bintray.com/packages/staticli/staticli/staticli
https://github.com/inconshreveable/go-update

**Comment by lucymhdavies** [comment]
Going to add a progress bar to pscli's version of this, then add the same code to lucli.

Undecided whether I'll stick with bintray for lucli. Might use GitHub Releases instead.

**Comment by WheresAlice** [comment]
It doesn't look like bintray actually adds much beyond what github releases does, and adding github releases should automatically list them on the Staticli website in the header. So yes, switching to github releases might be a good call.

**Comment by lucymhdavies** [comment]
I just went with Bintray initially because it's JFrog, and wanted to replicate what we're doing with Artifactory.

But yes, GitHub I think is a better place for this.

And the releases API looks like it should be able to do everything one could need.
https://developer.github.com/v3/repos/releases/

**Comment by WheresAlice** [comment]
Things are about to get very meta.  Staticli now has functionality to release versions of itself

https://github.com/staticli/staticli/commit/00daaa3c8d04d543675a7891d9f13598ec849850

Still to do - update all the docs to point to github releases, remove bintray, and add auto-updating.

**Comment by WheresAlice** [comment]
(it needs a personal token generating at https://github.com/settings/tokens/new with the scope of "repo" and saving to the github_api file in order to use this)

**Comment by WheresAlice** [comment]
As of v1.1.1 `staticli version` now checks for availability of new versions

Still to do - add a command to auto-update (still need to work out how to tell what architecture the current staticli binary is and therefore which asset to download)

**Comment by WheresAlice** [comment]
release 1.2.0 adds the update command, full resolving this issue
