### ISSUE TITLE
Request: staticli jekyll

### ISSUE THREAD

**Issue by lucymhdavies** [staticli/staticli#20]
e.g. `staticli jekyll new my-awesome-site`

**Comment by WheresAlice** [comment]
Added in staticli release 1.4.0

I'm using the `jekyll/jekyll` docker image so it won't handle file ownership correctly, and it's not configured to put gems into a vendor subdirectory so it has to download them every single run.  But the basics are there.

**Comment by WheresAlice** [comment]
released 1.5.2 to resolve the file ownership issue and cache gems on the host (needs internet access  on the first run, but it does anyway to download the image).  Closing this ticket as complete.
