### ISSUE TITLE
Release process isn't atomic

### ISSUE THREAD

**Issue by WheresAlice** [staticli/staticli#21]
Initiating a release on a low-bandwidth connection causes a new release to be made available and then uploads to it fail.  This means that staticli will see a new release and be unable to update to it.  Which may or may not go horribly wrong.

It looks like we should be able to mark a release as not being ready yet until the uploads are complete.

**Comment by lucymhdavies** [comment]
Yep. Just encountered this issue myself, attempting to update before it was ready. Oops.

**Comment by WheresAlice** [comment]
Getting CI working as per #8 is also going to help with this because that should be a much faster connection.

**Comment by WheresAlice** [comment]
GoReleaser solves this

It creates the new release, then it uploads the binaries, and then it makes the release public.
