### ISSUE TITLE
Fixing cali

### ISSUE THREAD

**Issue by edupo** [staticli/staticli#36]
fyi I'm doing [some rework](https://github.com/edupo/cali/tree/fix-image) of cali so that it allows you to login in any container as your own user.

I hope you may find that interesting.

**Comment by WheresAlice** [comment]
Ooh nice, I'm definitely interested in that.  There's an issue in Cali raised around standardising the handling of UID/GID which sounds related to this - and it would be good to track this there https://github.com/skybet/cali/issues/5

**Comment by lucymhdavies** [comment]
Yes, we definitely need a good standard way of doing this in cali, which doesn't require much from a developer.

Current ideas involve passing in env vars (which isn't a good solution), or user namespacing (which we can't guarantee is enabled everywhere).

**Comment by WheresAlice** [comment]
@edupo the canonical version of cali is actually the skybet/cali repo (we're trying to fix that / make it clearer). Would you be able to raise your PRs against the skybet/cali version?  The skybet/cali version is quite a long way ahead of Adam's earlier version now, and is the best place to be working on this.

**Comment by edupo** [comment]
No problem. I didn't knew that the repo was continued.
Mine has already been deviated too.
We will need to agree on new features before I do PR's since we are already using my version in my team.
