### ISSUE TITLE
Cannot self-update from 1.8.7 (macOS)

### ISSUE THREAD

**Issue by lucymhdavies** [staticli/staticli#58]
```
$ staticli -d update
INFO[0000] staticli v1.8.7
DEBU[0000] Build Details                                 BuildTime="2019-02-06T17:23:33Z" Version=1.8.7
DEBU[0000] Git Details                                   BuildCommit=b283e15
DEBU[0000] Latest version is: 1.8.9
FATA[0000] Unable to update: Unable to get update URL: Unable to find release asset for darwin amd64
```

I suspect this is because the new artifacts are named staticli.Darwin.x86_64.tar.gz whereas the old was named staticli.darwin.amd64

(Updating manually is, of course, fine)

**Comment by WheresAlice** [comment]
I should probably have checked that - I assumed the goreleaser config changes weren't meaningful.

I'll try and take a look at this this week. Hopefully it's just another small goreleaser config change required.
