### ISSUE TITLE
Fix travis-ci integration

### ISSUE THREAD

**Issue by WheresAlice** [staticli/staticli#8]

**Comment by lucymhdavies** [comment]
My Travis CI stuff in lucli is basically just "build & make sure it runs"

Actually getting deployments to bintray looks easy enough
https://docs.travis-ci.com/user/deployment/bintray/

And I might copypaste your code if you get this working before me :)

**Comment by WheresAlice** [comment]
I've modified my version of your makefile enough that your travisci code wasn't working for me.  I'll have a go at

**Comment by WheresAlice** [comment]
I had another go at this. The issue now is that travisci is running `go get` and then silently running `go build` which fails because of the docker dependency issues as noted in #2 

We need to work out how to stop travisci doing this.

**Comment by lucymhdavies** [comment]
bah. `go get` in docker later in the build seems to work though, otherwise we wouldn't be able to build new versions.

Just `go get` outside the container which isn't?

**Comment by WheresAlice** [comment]
I'm not convinced it's the `go get` that's the problem. I suspect it's pulling in the problematic dependency with the `go get` and then failing on a `go build`. But I don't see the need to do either of those, so I'll see if travisci can be told to just run the makefile and do everything in docker.

**Comment by WheresAlice** [comment]
ok, bit of a brain dump here.

Switching the language from go to cpp in travis.yml stops the issue with dependencies in whatever Travis-CI is trying to do.  However since there is then no GOPATH or suchlike, we're then forced to rethink mounts and volumes being used in the docker containers.

What I want to do at some point is completely rewrite the Makefile such that everything runs inside docker without caring where the repo is checked out but setting a sensible GOPATH and creating that directory if it doesn't exist.  That way we still benefit from having GOPATH mounted and therefore reusing downloaded src.

But it might be a while before I get around to doing this.

**Comment by WheresAlice** [comment]
I've switched to using `dep` for dependency management, and locked down access to the master branch, and made only the master branch do releases.  In theory this is all working now, but we need to actually do a new release of something to properly test it.

**Comment by WheresAlice** [comment]
so close now!  The limiting of only building new releases to the master branch is broken, but everything else seems to be mostly working.
