### ISSUE TITLE
Target specific versions of rake-preview docker image

### ISSUE THREAD

**Issue by WheresAlice** [staticli/staticli#9]
We're currently not targeting a specific version, which means when I used staticli on my desktop where I'd been developing the docker image I got an error because I had an old version of the docker image.

**Comment by lucymhdavies** [comment]
Personally, I think this is a bug in Cali.

i.e. Cali default behaviour should be to attempt to pull an image before running it.

(c *DockerClient).StartContainer does attempt a pull:

https://github.com/skybet/cali/blob/master/docker.go#L193-L195
```
	if err := c.PullImage(c.Conf.Image); err != nil {
		return "", fmt.Errorf("Failed to fetch image: %s", err)
	}
```


But the PullImage function will actually do nothing if the image already exists:

https://github.com/skybet/cali/blob/master/docker.go#L358-L361

```
// PullImage - Pull an image locally
func (c *DockerClient) PullImage(image string) error {

	if !c.ImageExists(image) {
```

Personally, I feel that default Cali behavior here should be to try to pull the image regardless.

**Comment by WheresAlice** [comment]
I'm frequently working on low-bandwidth internet connections so I wouldn't want it to pull the image every time, only when the version I've targeted isn't available locally.

**Comment by lucymhdavies** [comment]
Good point 🤔 

Perhaps "always try to pull the image" is not what I meant.

Perhaps what I mean is:
* Check if use has requested not to pull the image (e.g. with --no-pull-images, and the equivalent option in a cali config file)
* Attempt to pull the image (if you already have the image, moby just returns success)
* If that fails, only then check if the user already has a version of the image

**Comment by WheresAlice** [comment]
Closing won't-fix.  We can now target specific tags, and the user can delete old versions of images if they want.
